server:
  port: 8082

spring:
  cloud:
    discovery:
      enabled: true
  application:
    name: auth-service

jwt:
  secret: ${JWT_SECRET:mySecretKey}
  expiration: ${JWT_EXPIRATION_MS:3600000} # 1 hour in milliseconds
  refreshExpirationMs: ${JWT_REFRESH_EXPIRATION_MS:2592000000} # 30 days in milliseconds

