server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/user-service/**
        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/order-service/**