server:
  port: 8083

spring:
  cloud:
    discovery:
      enabled: true
  application:
    name: user-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/requestme
    username: requestme
    password: requestme